# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'XWKitDemo' do
pod 'SDWebImage'
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'Masonry'
pod 'INSPullToRefresh'
pod 'MJExtension'
pod 'CTAssetsPickerController'
end

target 'XWKitDemoTests' do

end

target 'XWKitDemoUITests' do

end

